[config]
skip_core_tasks = true

[tasks.default]
description = "Alias for \"firmware\""
workspace = false
dependencies = ["firmware"]

[tasks.firmware]
description = "Build flight controller firmware for the target system."
workspace = false
cwd = "./r4-firmware"
command = "cargo"
args = ["build"]

[tasks.unit-test]
description = "Unit test platform-independent code on the host system."
workspace = false
cwd = "./r4-x"
command = "cargo"
args = ["test"]
