[config]
skip_core_tasks = true

[tasks.default]
description = "Alias for \"firmware\""
workspace = false
dependencies = ["firmware"]

[tasks.firmware]
description = "Build flight controller firmware for the target system."
workspace = false
cwd = "./quadrotor-firmware"
command = "cargo"
args = ["build"]

[tasks.run]
description = "Run flight controller firmware using probe-rs."
workspace = false
cwd = "./quadrotor-firmware"
command = "cargo"
args = ["run"]

[tasks.unit-test]
description = "Unit test platform-independent code on the host system."
workspace = false
cwd = "./quadrotor-x"
command = "cargo"
args = ["test"]
